### ISSUE TITLE
Newbie help + problems installing + nix flake

### ISSUE THREAD

**Issue by NomisIV** [TravisDavis-ops/wayplover#5]
I'm looking into learning stenography as a part of a school project, and my setup also consists of a Planck keyboard and the wayland graphical environment. As far as I understand, this project is my best shot at getting started, but since I'm new to it all, I don't understand the caveats you have listed. Are they trivial enough to work around, or will my learning experience suffer from them? 

Also, I'm having problems installing wayplover with `cargo install wayplover` (it fails when compiling bitvec, for some reason), so I'm currently working on a nix flake for the project. I can submit a PR with this if you are interested.

**Comment by TravisDavis-ops** [comment]
Thank for letting me know, the cavets are a problem for you ,  Sorry you can only get to about  here [last  lessons i did using this](https://sites.google.com/site/learnplover/lesson-5-prefix-and-suffix-strokes) because the it not possable to do some of the words.
afaik plover does work in some xwayland applications.

**Comment by NomisIV** [comment]
Thanks for the honest answer! I'll consider my options.

**Comment by TravisDavis-ops** [comment]
I need to learn more about flakes, im really new to nix.  sharing that flake would be appreciated.

**Comment by NomisIV** [comment]
I sent a PR. I couldn't test if the program builds successfully, since I haven't set up Gemini-PR on my Planck (the program crashes in `ui.rs:109`, probably because it can't find the device file for the keyboard), so I recommend trying everything to make sure that it works correctly before merging.

**Comment by TravisDavis-ops** [comment]
Thanks I'll through it some time this week.

**Comment by TravisDavis-ops** [comment]
Hey with your flake everything builds perfectly thank you so much,
